substitutions:
  name: "athom-relay-board-x8"
  friendly_name: "Athom Relay Board x8"
  project_name: "athom.relay-board-x8"
  project_version: "1.0"
  relay1_restore_mode: RESTORE_DEFAULT_OFF
  relay2_restore_mode: RESTORE_DEFAULT_OFF
  relay3_restore_mode: RESTORE_DEFAULT_OFF
  relay4_restore_mode: RESTORE_DEFAULT_OFF
  relay5_restore_mode: RESTORE_DEFAULT_OFF
  relay6_restore_mode: RESTORE_DEFAULT_OFF
  relay7_restore_mode: RESTORE_DEFAULT_OFF
  relay8_restore_mode: RESTORE_DEFAULT_OFF

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: esp8285
  restore_from_flash: true

api:

ota:

logger:

web_server:
  port: 80

wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:

dashboard_import:
  package_import_url: github://humancityheath/mqtt_riverside_transfer/athom-relay-board-x8.yaml

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

  - platform: gpio
    name: "${friendly_name} IO2"
    disabled_by_default: true
    pin:
      number: GPIO2
      mode: INPUT_PULLUP
      inverted: true

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"
    disabled_by_default: true

  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s

button:
  - platform: restart
    id: restart_button
    name: "${friendly_name} Restart"

switch:
  - platform: gpio
    name: "${device_id} r1"
    pin: GPIO16
    id: relay1
    restore_mode: ${relay1_restore_mode}

  - platform: gpio
    name: "${friendly_name} - 2"
    pin: GPIO14
    id: relay2
    restore_mode: ${relay2_restore_mode}

  - platform: gpio
    name: "${friendly_name} - 3"
    pin: GPIO12
    id: relay3
    restore_mode: ${relay3_restore_mode}

  - platform: gpio
    name: "${friendly_name} - 4"
    pin: GPIO13
    id: relay4
    restore_mode: ${relay4_restore_mode}

  - platform: gpio
    name: "${friendly_name} - 5"
    pin: GPIO15
    id: relay5
    restore_mode: ${relay5_restore_mode}

  - platform: gpio
    name: "${friendly_name} - 6"
    pin: GPIO0
    id: relay6
    restore_mode: ${relay6_restore_mode}

  - platform: gpio
    name: "${friendly_name} - 7"
    pin: GPIO4
    id: relay7
    restore_mode: ${relay7_restore_mode}

  - platform: gpio
    name: "${friendly_name} - 8"
    pin: GPIO5
    id: relay8
    restore_mode: ${relay8_restore_mode}

light:
  - platform: status_led
    name: "${friendly_name} Status LED"
    disabled_by_default: true
    pin:
      inverted: true
      number: GPIO2

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      disabled_by_default: true
