substitutions:
  friendly_name: "Relay ${prefix_id}"
  project_name: "r.${prefix_id}"
  project_version: "1.0"
  relay1_restore_mode: RESTORE_DEFAULT_OFF
  relay2_restore_mode: RESTORE_DEFAULT_OFF
  relay3_restore_mode: RESTORE_DEFAULT_OFF
  relay4_restore_mode: RESTORE_DEFAULT_OFF
  relay5_restore_mode: RESTORE_DEFAULT_OFF
  relay6_restore_mode: RESTORE_DEFAULT_OFF
  relay7_restore_mode: RESTORE_DEFAULT_OFF
  relay8_restore_mode: RESTORE_DEFAULT_OFF

esp8266:
  board: esp8285
  restore_from_flash: true

ota:

logger:
 level: ERROR

web_server:
  port: 80

captive_portal:

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"
    disabled_by_default: true

button:
  - platform: restart
    id: restart_button
    name: "${friendly_name} Restart"

switch:
  - platform: gpio
    name: "${prefix_id} r1"
    pin: GPIO16
    id: relay1
    restore_mode: ${relay1_restore_mode}

  - platform: gpio
    name: "${prefix_id} r2"
    pin: GPIO14
    id: relay2
    restore_mode: ${relay2_restore_mode}

  - platform: gpio
    name: "${prefix_id} r3"
    pin: GPIO12
    id: relay3
    restore_mode: ${relay3_restore_mode}

  - platform: gpio
    name: "${prefix_id} r4"
    pin: GPIO13
    id: relay4
    restore_mode: ${relay4_restore_mode}

  - platform: gpio
    name: "${prefix_id} r5"
    pin: GPIO15
    id: relay5
    restore_mode: ${relay5_restore_mode}

  - platform: gpio
    name: "${prefix_id} r6"
    pin: GPIO0
    id: relay6
    restore_mode: ${relay6_restore_mode}

  - platform: gpio
    name: "${prefix_id} r7"
    pin: GPIO4
    id: relay7
    restore_mode: ${relay7_restore_mode}

  - platform: gpio
    name: "${prefix_id} r8"
    pin: GPIO5
    id: relay8
    restore_mode: ${relay8_restore_mode}

light:
  - platform: status_led
    name: "${friendly_name} Status LED"
    disabled_by_default: true
    pin:
      inverted: true
      number: GPIO2

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      disabled_by_default: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_ip
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: !secret mqtt_topic
